### ISSUE TITLE
Entity access for groups and group content

### ISSUE THREAD

**Issue by RoySegall** [Gizra/og#3]
OG supply basic permission(og_access extends it). For now the permission is a content entity. But this could be a config entity since we want to export permission for roles.

This a discussion we can do here but will provide solution via code.

**Comment by zerolab** [comment]
Is this still relevant?
OG permissions are exportable to code. And #243 exposes the UI for roles and permissions

**Comment by pfrenssen** [comment]
I think this can be closed because it has been implemented already. The permissions are no longer entity based, we have an event that can be subscribed to to define permissions (`PermissionEvent`), which will supply `GroupPermission` objects. Examples of this can be found in `OgEventSubscriber`.

We don't have OG Access yet, which I think provided a UI for defining permissions? This is out of scope for this issue though.
