### ISSUE TITLE
EFQ support

### ISSUE THREAD

**Issue by RoySegall** [Gizra/og#4]
OG audience field(AKA og_group_ref) field is empty but the values is kept in the og membership entity. In drupal 7 we had entity field query alter hook that do for us the work. This is a also something we need to import.

**Comment by mradcliffe** [comment]
I am not sure if you'll be able to do this. You would need to override the EFQ service now, I think.

In practice I always just used the database transaction layer directly instead of EFQ because it was faster, more accurate (7.x-1.x branch),  and I did not need to worry about fields. I think we could just recommend this approach instead of worrying about trying to support EFQ.

**Comment by RoySegall** [comment]
In the 2.x we handled this. If people would use the module updater, that can handle EFQ update, they need to to change all the EFQ that the updater update for them.

**Comment by pfrenssen** [comment]
I'm reviewing the work that absolutely needs to be done to make a first alpha release.

Possibly I don't fully understand the implications of this, but it seems that this is more a DX improvement than a hard blocker for releasing the alpha. There are already multiple ways to get the data about the group audience of a particular group without needing to have this available on the entity.

If I am mistaken feel free to add back the label.

**Comment by amitaibu** [comment]
I believe this one can be closed. We do have EntityQuery support, as we either have a regular reference field, or `OgMembership`
