### ISSUE TITLE
Guidance for new site - Organic Groups vs Group? D7 vs D8?

### ISSUE THREAD

**Issue by ebrittwebb** [Gizra/og#469]
I read the [Roadmap issue](https://github.com/Gizra/og/issues/240), but wanted to ask this question slightly differently. 

I'm building a story telling platform that combines passions for genealogy, family photography, and social media, and brings them to a whole new and integrated level of telling stories about your ancestors, and celebrating the life of an individual who has just passed away. I'm building this on Drupal with Organic Groups as the main organizing construct. Every Album - whether
it's a family tree, a single individual, or even a photo album - is instantiated as an OG. I'm writing about it and will launch it at [www.greatalbum.net](www.greatalbum.net).

Right now, I'm building the prototype on D7+OG because it's stable and it's essential that any piece of content (family/individual/event/place/story/media/etc.) be allowed to exist in more than Album(OG), and that an Album's content can be marked public or private. The goal is to launch the prototype in April, and then launch the production v1 site in June or July. I'd love the public launch to be on D8+OG, but I'm not sure how realistic that is, since OG v8.x is currently 1.0-alpha2.

So, my questions are:
1. Am I correct to understand that [Group](https://www.drupal.org/project/group) module does not allow content to exist in more than one group at a time, and hence based on my requirement, [OG](https://www.drupal.org/project/og) is the better choice?
2. I gather from [issue 237](https://github.com/Gizra/og/issues/237) that OGs cannot be made private yet, and that someone would need to fund 1-2 week effort to port og_access to D8, right? 
2. Besides the private groups blocker, should I assume that [OG 8.x-1.0-alpha2](https://www.drupal.org/project/og/releases/8.x-1.0-alpha2) is not stable enough to use for a production site, and that I should stick with [OG 7.x-2.10](https://www.drupal.org/project/og/releases/7.x-2.10) for now, and wait on the benefits of Drupal8 until OG matures at least to RC1? 

Any guidance would be greatly appreciated!

**Comment by pfrenssen** [comment]
1. I am not sure if Group allows content to be shared in multiple groups.
2. OG access is being worked on currently in #242. Any help is always appreciated!
3. It is never recommended to use alpha software in production, but in practice this depends on your technical expertise and willingness to support backwards compatibility breaks in the future. If you expect the module to "just work" and keep working in the future without requiring any adaptions when new versions are released then definitely do not use the D8 version yet. But on the other hand some projects are already using it in production and it has proven to be quite stable and performant. But it is not feature complete, and there might be some hidden dragons that might pop up in the future to wreck your day. As always when deciding to use an alpha or beta module, make a risk assessment, and try to cover your own use cases for which you use the module with tests, so that you can easily evaluate any possible breakage in future versions.
