### ISSUE TITLE
Add documentation for OG permission layer

### ISSUE THREAD

**Issue by MPParsley** [Gizra/og#510]
Edit: we need to document how the OG permissions layer works.

original report:

> 
> https://github.com/Gizra/og/blob/8.x-1.x/src/EventSubscriber/OgEventSubscriber.php#L175 defines the permission format as `create $bundle_id content` for nodes.
> 
> We should update the permission format to support content entities other than node. 
> 
> This is a follow up from #181 where we added the ValidOgMembershipReferenceConstraintValidator.
> See https://github.com/Gizra/og/pull/181/files#r117715404

**Comment by pfrenssen** [comment]
There seems to be a misunderstanding here. OG doesn't deal with group content permissions in the format of strings, as is done by Drupal core. We had this problem in the past that we needed a structural way to discover and use permissions which is not depending on a permission string.

In OG we support all kinds of entities, and we need our own permission layer so that we can let users do different kinds of actions depending on their role in their groups. The problem we encountered was that we cannot easily reuse the permission system from core since they are string based and we cannot derive the entity type and operation from them.

For example:

The core Node module defines a permission like "delete own article content" - for OG seeing this string it is impossible to understand what is meant by this. We could discover the words "delete" and "own" and infer the operation and the scope from it, but the bundle and entity type can not be derived easily. In fact the entity type "node" doesn't even appear in the string!

The second problem we had was that for our group content we need more operations that core typically supports. Typical examples are the permissions to join and leave groups, add users to groups, etc. We also want our users to be able to easily implement their own permission systems. For example a site might want to have a permission that have the "premium" role to "get a free t-shirt".

These use cases are very difficult to solve when we are defining a permission as a machine name and a human readable description as is done in core. What we needed was a `Permission` object that has separate properties representing the machine name (ID), description, operation, entity type and bundle. This has been implemented in the `GroupContentOperationPermission` class.

So this request is asking to change the string format from `create $bundle_id content` to something else so that we can support content entities other than nodes. I'm happy to say that all of this has already been implemented. But trying to get the permissions by passing the string ID like is done in core is not the right way. Here is how to do it:

If you are looking for the permissions for nodes (i.e. the `create $bundle_id content` permission mentioned in the issue summary):

```
// Let's say in our project our group type is the custom entity type `group` with
// bundle `class`.
$group_entity_type_id = 'group';
$group_bundle_id = 'class';

// We want to get the list of permissions for group content type 'node' and bundle 'news'.
$group_content_bundle_ids = [
  'node' => ['news'],
];

// Retrieve all permissions that exist for our group content in our chosen group type.
$permission_manager = \Drupal::service('og.permission_manager');
$permissions = $permission_manager->getDefaultEntityOperationPermissions($group_entity_type_id, $group_bundle_id, $group_content_bundle_ids);
```

Now our `$permissions` array will contain a list of all possible permissions that are defined for our group content inside our group type, for example it might look like this:

```
[
    "view news revisions" => Drupal\og\GroupContentOperationPermission {#4480},
    "revert news revisions" => Drupal\og\GroupContentOperationPermission {#4482},
    "delete news revisions" => Drupal\og\GroupContentOperationPermission {#4484},
    "share news content" => Drupal\og\GroupContentOperationPermission {#4486},
    "unshare news content" => Drupal\og\GroupContentOperationPermission {#4488},
    "create news content" => Drupal\og\GroupContentOperationPermission {#4495},
    "edit own news content" => Drupal\og\GroupContentOperationPermission {#4496},
    "edit any news content" => Drupal\og\GroupContentOperationPermission {#4497},
    "delete own news content" => Drupal\og\GroupContentOperationPermission {#4498},
    "delete any news content" => Drupal\og\GroupContentOperationPermission {#4499},
]
```

Now we want to filter this down to only have the permissions dealing with the `create` operation, so we can do:

```
$permissions = array_filter($permissions, function ($permission) {
  return $permission->getOperation() === 'create';
});
```

This will give us the result we want, `$permissions` now only contains the relevant permission:

```
[
    "create news content" => Drupal\og\GroupContentOperationPermission {#4463},
]
```

If you want to use this for any other group content entity type instead of nodes, just change `$group_content_bundle_ids` accordingly.

**Comment by pfrenssen** [comment]
So while this is already solved, it seems like it is not clear how to use this. Shall we change this issue to improve the documentation on how to work with OG permissions programmatically? I think it could perhaps be very useful to have a markdown document that explains the concept of permissions in OG with some example code on how to use it.

What do you think?

**Comment by MPParsley** [comment]
@pfrenssen,

The issue in #181 was originally a bug as two different string formats were used:
- create $bundle_id content
- create [entity-type] [bundle]

Providing the documentation for GroupContentOperationPermission sure makes sense. I updated this issue title accordingly.

I also opened a PR to add userAccessGroupContentEntityOperation to the OgAccessInterface (#513).

**Comment by pfrenssen** [comment]
OK! I plan to sprint on OG at Drupal Dev Days, I will have more time to look deeper in the open PRs then.

**Comment by MPParsley** [comment]
@pfrenssen, with #243 we can list permissions for node operations but ogmenu_instance isn't listed there. How can we list ogmenu_instance under the group permissions (cfr. node entities)?

**Comment by pfrenssen** [comment]
If OG Menu requires custom permissions then it should implement an event listener that announces them. I see it is already doing this, it has `OgMenuEventSubscriber::provideDefaultOgPermissions()` which provides its group level permission.

The entity operation permissions are covered by the blanket implementation which covers all group content (ref `OgEventSubscriber::getDefaultEntityOperationPermissions()`). If OG Menu wants to customize these it can override the generic values by implementing their own, as documented in `OgEventSubscriber::getSubscribedEvents()`:

```
    return [
      PermissionEventInterface::EVENT_NAME => [
        // Provide a higher priority for the generic event subscriber so that it
        // can run first and set default values for all supported entity types,
        // which can then be overridden by other subscribers that set module
        // specific permissions.
        ['provideDefaultOgPermissions', 10],
        ['provideDefaultNodePermissions'],
      ],
    ];
```
