### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by MPParsley** [Gizra/og#531]
See https://keepachangelog.com/en/1.0.0/

**Comment by pfrenssen** [comment]
I see this as having no value and just creating additional work for the maintainers.

**Comment by MPParsley** [comment]
As long as we're on GitHub it will be available here https://github.com/Gizra/og/releases

**Comment by pfrenssen** [comment]
Yes that was my idea too, I was maybe a bit quick to dismiss it without explanation. For Drupal projects the common approach is to list the changes in the release notes. For OG we publish these on Github but also in the Drupal project page. See for example here are the release notes for the recent alpha3 release: https://www.drupal.org/project/og/releases/8.x-1.0-alpha3

If the project has a stable release we are also expected to create change records for every change. These are better than a normal changelog since they are searchable and can provide code examples and links to the relevant tickets. For as long as we are in alpha or beta changes are pretty much expected and don't need to have change records.

It is not so common any more to provide changelogs because there are much better ways to track changes with the rise of version control systems and ticket trackers. For example the Drupal core team has decided to stop updating their changelog last year after using it for decades: see https://www.drupal.org/node/2647824
