### ISSUE TITLE
OGMembership entity_id is defined as String

### ISSUE THREAD

**Issue by meecect** [Gizra/og#557]
I was working on a integrating Feeds and OG.  I managed to import groups fine, as they are just nodes.  I also got Group Content, as they are just Entity References.

Now I am working on memberships.  Theoretically, the Feeds generic EntityProcessor should work and it does get me halfway there but I had some issues referencing the group.

I created this issue in their queue:

https://www.drupal.org/project/feeds/issues/3041594

Where it was suggested that the reason the out of the box Entity Reference mapper doesn't function is that the entity_id field is defined as a string and not as an entity reference:

`$fields['entity_id'] = BaseFieldDefinition::create('string')
  ->setLabel(t('Group entity ID'))
  ->setDescription(t('The entity ID of the group.'));`

I was just wondering what the reason for that is?  The reference to the user is an entity reference, for example:

`    $fields['uid'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Member User ID'))
      ->setDescription(t('The user ID of the member.'))
      ->setSetting('target_type', 'user');
`

I realize there is probably a really good reason for this, I was just curious what the thought was.

**Comment by meecect** [comment]
hmm, I was reading some related issues in the Group module...it looks like they had some similar discussion.  I'm guessing it allows you to reference non-content entities with id's that are not integers?

Also, using an EntityReference field introduces some other problems, I assume?

**Comment by pfrenssen** [comment]
The reason is that with a entity reference field you can only reference one single entity type. You need to specify the `target_type`. This would make it impossible to have group types of different entity types.

In older versions of OG all groups were of the Node entity type and it would have been possible to use a standard entity reference field. But since version 2.x for Drupal 7 we allow any entity type to become a group type, so we cannot use entity references any more.
