### ISSUE TITLE
Error while running Drupal 8.8.x DB updates

### ISSUE THREAD

**Issue by claudiu-cristea** [Gizra/og#572]
```
>  [notice] Update started: system_update_8803
>  [error]  The cache backend must support cache tag invalidation.
>  [error]  Update failed: system_update_8803
...
 [error]  Update aborted by: system_update_8803
 [error]  Finished performing updates.
```

This happens because in `MembershipManager` this assertion is triggered:

```php
public function __construct(EntityTypeManagerInterface $entity_type_manager, OgGroupAudienceHelperInterface $group_audience_helper, CacheBackendInterface $cache) {
  assert($cache instanceof CacheTagsInvalidatorInterface, 'The cache backend must support cache tag invalidation.');
  ...
}
```

But during updates the cache backend, injected as `$cache` in the constructor, is an instance of the class `\Drupal\Core\Update\UpdateBackend` and that doesn't implement `CacheTagsInvalidatorInterface`.

**Comment by pfrenssen** [comment]
This is actually a bug in core, in `system_update_8803()` a new module is being installed, which fires a complete container rebuild. This is a very risky operation since during `hook_update` the database is in a non-working state.

They should probably move this to a `post_update`. The change was added in https://www.drupal.org/project/drupal/issues/3084983

**Comment by Berdir** [comment]
I'm not sure that assert makes sense. All cache backends support tags, it's part of the API. But most don't need to implement CacheTagsInvalidatorInterface because they rely on the checksum for their implementation. Unless you'd explicitly call ->invalidateTags() on the backend, you don't need to check for that.

**Comment by pfrenssen** [comment]
We're calling it through `CacheTagsInvalidator::invalidateTags()` whenever an `OgMembership` entity is invalidated (through `EntityBase::invalidateTagsOnSave()` and `::invalidateTagsOnDelete()`).

The `MembershipManager` is keeping these entities in its local static cache so we need to ensure that the static cache is invalidated correctly when a membership changes. Otherwise the `MembershipManager` might be returning stale data.

**Comment by Berdir** [comment]
You call Cache::invalidateTags(), which goes through the cache tags invalidator service which then passes it to all cache backends and services with the tag. Again, all cache backends are expected to support cache tags, it's not your job to check it, not like this.

**Comment by pfrenssen** [comment]
Ah yeah I see it now, there are 2 possible ways, the backends that use checksums do not need to implement `CacheTagsInvalidatorInterface` directly (like you said earlier).

OK we can get rid of this assert.

**Comment by xjm** [comment]
If this is a core bug, can we get a core issue? :)

**Comment by claudiu-cristea** [comment]
@xjm it seems more an Organic Groups issue, as per @Berdir's comment.

**Comment by xjm** [comment]
So (for people finding this issue from the release notes), a PR has been merged for OG to resolve this issue: https://github.com/Gizra/og/pull/573

No new release has been created to include this change, so users encountering this issue should update to the latest HEAD of this project before updating to Drupal 8.8.0. Is that correct?

**Comment by pfrenssen** [comment]
There is a new issue to track compliance with Drupal 8.8: #576 

The most pressing issues have been solved already, so if someone needs their project to be compatible with Drupal 8.8 as soon as possible, please track `dev-8.x-1.x` for the time being.

**Comment by claudiu-cristea** [comment]
@xjm now there's a new [8.x-1.0-alpha4](https://github.com/Gizra/og/releases/tag/8.x-1.0-alpha4) release fully compatible with Drupal 8.8.0.
