### ISSUE TITLE
[Feature Request] More options in og_access

### ISSUE THREAD

**Issue by jerrac** [Gizra/og#639]
I just did some quick manual tests on a clean Drupal 8.5.3 instance with the og_access branch referenced in this pull request: https://github.com/Gizra/og/pull/242. It seems to work well.

That said, the reason I'm looking into this now is that I'm trying to prototype an Intranet site for my workplace. One of the requirements is that I have more access levels that just the "public" or "private" that og_access provides.

Specifically:
* Visible to the world.
* Visible to authenticated site users.
* Visible to group members only.

og_access, plus not allowing anonymous users to view published content will give me the second two items. But that leaves the first item unfulfilled.

Would that list of options make sense to be included in og_access? If so, that's my feature request. :)

If not, how would you go about implementing those options in a seperate, custom, module? 

My initial thoughts are a checkbox field "Visible to the world", plus hook_node_access, if the checkbox field is true, then grant all, include anonymous, users view access. Otherwise go with whatever og_access, and the global permissions, say.

Thanks in advance. :)

**Comment by agallewale** [comment]
At least till Drupal 7.x, og_access provided all the three levels you had asked. I am using this already in production, for  a very popular drupal based community site that scales to 1.8  million visitors with 300+ groups.  I am yet to try 8.x , but if it is missing any of the levels it would be a regression from what used to be available.  You can try making your group public and see if it supports first level.

**Comment by jerrac** [comment]
Did it? A few years ago I was trying to use D7 for this same project and I think I had to use og_visibility to get close to what I needed. There was something still missing at the time, but I don't quite recall what...

From the looks of things, the change they are making is described here: https://github.com/Gizra/og/pull/242#issuecomment-590078108

**Comment by agallewale** [comment]
Hmm. in D7.x I am not using og_visibility. In fact by default every new content created is public or private as per the group settings. So if you have a public group , then the content is world viewable even if you are not member of site. Isn't that you want? I can understand now #242 can cause it different, but  atleast you can make group public explicitly and still achieve the same thing for new content?

**Comment by jerrac** [comment]
The issue is I'd like some content to not be world viewable, but be viewable to any authenticated user. 

So, say, a committee should only be seen by current employees. But some content would only be for committee/group members, and some would be for any employee. 

Currently, the way you would do that is by removing anonymous user access to your entire site, then the committee would make the any employee content public, and the group member only content private.

The thing is, we also need content to be visible to the world. Which means any public content is visible to the world.

Hopefully that explains what I'm after.

**Comment by agallewale** [comment]
We have similar setup and some workarounds.  First we distinguished from the existence of the committee group itself from content created by those committees.
1) A committee starts being a private group. Its existence is only known to the invited committee members.
2) At some point the committee decides to make its existence known to employees. At which point it creates another private group open to any employee.  It announces the charter of the group and link to this Employee only group on  a page visible to only employees.  The head/admin of the committee group is also admin of this new group.
3) Employees self subscribe to this group. Or for more important groups,  you can use bulk views admin script to subscribe all employees to this group automatically.
4) As the committee votes to make policy /content final, the Head of committee publishes the content to the employee group so they see a vetted content.  At this point the committee also decides if the content published is employee only (private) or world view-able (public)
5) You could also take another approach, depending on the content . If it is just text, instead of creating world viewable content in the group, you just create a content page outside the group and make it world viewable. And you can just create a link to that content to annouce to the employees that such content exist as such and such location.

So far it  has worked for us for last several years. Yes there is overhead of two group per purpose but we found it worked for us and after a while does not feel overhead at all. Also be aware that there is not always need to have 1x1 relationship with each commitee and employee group. There could be multiple committees but one employee group (or in lesser number) where committees publish their final content ready to be consumed by all employees.

**Comment by jerrac** [comment]
That is much more formal, and sensible, than I'd expect where I work. I'll have enough of a job just getting the idea started, I don't want to tackle pushing for more sensible workflows. :|

> At some point the committee decides to make its existence known to employees. At which point it creates another private group open to any employee. It announces the charter of the group and link to this Employee only group on a page visible to only employees. The head/admin of the committee group is also admin of this new group.

So, that's a private group, but the admin adds all the employees as members?

**Comment by agallewale** [comment]
The private group has only limited members. So Admin adds only the committee members to the group (which is typically less than 10). Then when a public group is created , the interested employees can self join. Or you can use the bulk admin module to add all employees as members to required group.

**Comment by MPParsley** [comment]
> og_access, plus not allowing anonymous users to view published content will give me the second two items. But that leaves the first item unfulfilled.

In #242 public groups are "Visible to the world."

If you have any suggestions wrt og_access you can discuss them in #242.
