### ISSUE TITLE
https://www.drupal.org/node/2151015

### ISSUE THREAD

**Issue by alexhass** [Gizra/og#72]

**Comment by dpi** [comment]
Please stop harassing Organic Groups by
- Cross posting to an issue tracker declared abandoned by the project.
- Posting issues on Github without useful information.
- Complaining you dont like Github
- Posting bump comments

You are being a menace

**Comment by alexhass** [comment]
If you do not cleanup the issue in d.o and just leave all issues unmaintained than you need to import all the 2K issues here. d.o is the place to maintain Drupal projects, not github. I do not read everytime if there is a note on project home about such a move that should not happen. Github gives us nothing than sync issues and cluttering of the community.

**Comment by dpi** [comment]
Try to improve your behaviour instead of posting political opinions in an unsuitable venue.

You know the decision has been made by the project already. Post useful Github issues instead of URLs to the Drupal.org issue tracker without any context.

Changing your comment in #71 from "Github SUXX"  to "You destroy the Drupal community otherwise." after I posted my comment is also a non-constructive activity.

**Comment by alexhass** [comment]
I think your are missing the points.

The queue on d.o is full of issues that require attention and fixes.#
There are tons of patches in the queue and they stay there for an extended period of time.
Has Github a d.o Testbot? I'm not aware of this.
You require people to have two acounts where they only need one on d.o.

**Comment by alexhass** [comment]
I do not see a commit of the patch in https://www.drupal.org/node/2151015 here. Why are you closing this case without committing the bugfixes?

**Comment by amitaibu** [comment]
Thanks dpi.

yamlfd, desicion to move to github is in order to allow easier development. It's ok if you don't agree.

**Comment by alexhass** [comment]
d.o has the same Git like here. There is no difference. Excect Github runs no testbot what is a no-go
